var dir_ec8f0bfa7fdadfcc06ea5c771d837a1c =
[
    [ "000-test-main.cc", "000-test-main_8cc.html", "000-test-main_8cc" ],
    [ "001-operable.cc", "001-operable_8cc.html", "001-operable_8cc" ],
    [ "038-channel-occupancy-size.cc", "038-channel-occupancy-size_8cc.html", "038-channel-occupancy-size_8cc" ],
    [ "039-channel-members.cc", "039-channel-members_8cc.html", "039-channel-members_8cc" ],
    [ "040-lru-table.cc", "040-lru-table_8cc.html", "040-lru-table_8cc" ],
    [ "041-bitwise_ops.cc", "041-bitwise__ops_8cc.html", "041-bitwise__ops_8cc" ],
    [ "042-get-span.cc", "042-get-span_8cc.html", "042-get-span_8cc" ],
    [ "043-fwcounter.cc", "043-fwcounter_8cc.html", "043-fwcounter_8cc" ],
    [ "044-extract.cc", "044-extract_8cc.html", "044-extract_8cc" ],
    [ "045-transform-while-n.cc", "045-transform-while-n_8cc.html", "045-transform-while-n_8cc" ],
    [ "080-tracereader.cc", "080-tracereader_8cc.html", "080-tracereader_8cc" ],
    [ "081-tracereader-instr-id.cc", "081-tracereader-instr-id_8cc.html", "081-tracereader-instr-id_8cc" ],
    [ "082-branch-targets.cc", "082-branch-targets_8cc.html", "082-branch-targets_8cc" ],
    [ "083-decompress-stream.cc", "083-decompress-stream_8cc.html", "083-decompress-stream_8cc" ],
    [ "084-tracereader-eof.cc", "084-tracereader-eof_8cc.html", "084-tracereader-eof_8cc" ],
    [ "085-repeatable.cc", "085-repeatable_8cc.html", "085-repeatable_8cc" ],
    [ "140-single-dib-lookup.cc", "140-single-dib-lookup_8cc.html", "140-single-dib-lookup_8cc" ],
    [ "150-fetch-bandwidth.cc", "150-fetch-bandwidth_8cc.html", "150-fetch-bandwidth_8cc" ],
    [ "165-basic-btb-no-evict-on-unknown-target.cc", "165-basic-btb-no-evict-on-unknown-target_8cc.html", "165-basic-btb-no-evict-on-unknown-target_8cc" ],
    [ "166-issue296-basic-btb-no-mispredict-on-not-taken.cc", "166-issue296-basic-btb-no-mispredict-on-not-taken_8cc.html", "166-issue296-basic-btb-no-mispredict-on-not-taken_8cc" ],
    [ "200-rob-scheduling.cc", "200-rob-scheduling_8cc.html", "200-rob-scheduling_8cc" ],
    [ "300-retire-from-rob.cc", "300-retire-from-rob_8cc.html", "300-retire-from-rob_8cc" ],
    [ "400-cache-occupancy-size.cc", "400-cache-occupancy-size_8cc.html", "400-cache-occupancy-size_8cc" ],
    [ "401-hit-latency.cc", "401-hit-latency_8cc.html", "401-hit-latency_8cc" ],
    [ "402-miss-latency.cc", "402-miss-latency_8cc.html", "402-miss-latency_8cc" ],
    [ "403-read-bandwidth.cc", "403-read-bandwidth_8cc.html", "403-read-bandwidth_8cc" ],
    [ "404-fill-bandwidth.cc", "404-fill-bandwidth_8cc.html", "404-fill-bandwidth_8cc" ],
    [ "405-fill-eviction.cc", "405-fill-eviction_8cc.html", "405-fill-eviction_8cc" ],
    [ "406-mshr-merge.cc", "406-mshr-merge_8cc.html", "406-mshr-merge_8cc" ],
    [ "410-queue-collision.cc", "410-queue-collision_8cc.html", "410-queue-collision_8cc" ],
    [ "411-queue-translation-hit.cc", "411-queue-translation-hit_8cc.html", "411-queue-translation-hit_8cc" ],
    [ "412-queue-translation-miss.cc", "412-queue-translation-miss_8cc.html", "412-queue-translation-miss_8cc" ],
    [ "413-hit-under-miss.cc", "413-hit-under-miss_8cc.html", "413-hit-under-miss_8cc" ],
    [ "414-tag-check-bound.cc", "414-tag-check-bound_8cc.html", "414-tag-check-bound_8cc" ],
    [ "420-issue-prefetch.cc", "420-issue-prefetch_8cc.html", "420-issue-prefetch_8cc" ],
    [ "421-prefetch-fill-level.cc", "421-prefetch-fill-level_8cc.html", "421-prefetch-fill-level_8cc" ],
    [ "422-prefetch-hit.cc", "422-prefetch-hit_8cc.html", "422-prefetch-hit_8cc" ],
    [ "423-prefetcher-activate.cc", "423-prefetcher-activate_8cc.html", "423-prefetcher-activate_8cc" ],
    [ "424-duplicate-prefetch.cc", "424-duplicate-prefetch_8cc.html", "424-duplicate-prefetch_8cc" ],
    [ "425-useless-prefetch.cc", "425-useless-prefetch_8cc.html", "425-useless-prefetch_8cc" ],
    [ "426-internal-pq-size.cc", "426-internal-pq-size_8cc.html", "426-internal-pq-size_8cc" ],
    [ "431-merge-prefetch.cc", "431-merge-prefetch_8cc.html", "431-merge-prefetch_8cc" ],
    [ "432-prefetch-metadata.cc", "432-prefetch-metadata_8cc.html", "432-prefetch-metadata_8cc" ],
    [ "441-replacement-bypass.cc", "441-replacement-bypass_8cc.html", "441-replacement-bypass_8cc" ],
    [ "442-replacement-interface.cc", "442-replacement-interface_8cc.html", "442-replacement-interface_8cc" ],
    [ "451-next-line-behavior.cc", "451-next-line-behavior_8cc.html", "451-next-line-behavior_8cc" ],
    [ "452-ip-stride-behavior.cc", "452-ip-stride-behavior_8cc.html", "452-ip-stride-behavior_8cc" ],
    [ "453-va-ampm-lite-behavior.cc", "453-va-ampm-lite-behavior_8cc.html", "453-va-ampm-lite-behavior_8cc" ],
    [ "600-ptw-path.cc", "600-ptw-path_8cc.html", "600-ptw-path_8cc" ],
    [ "601-multiple-inflight-walks.cc", "601-multiple-inflight-walks_8cc.html", "601-multiple-inflight-walks_8cc" ],
    [ "602-walk-latency.cc", "602-walk-latency_8cc.html", "602-walk-latency_8cc" ],
    [ "603-pte-page-correctness.cc", "603-pte-page-correctness_8cc.html", "603-pte-page-correctness_8cc" ],
    [ "801-vmem-duplicated.cc", "801-vmem-duplicated_8cc.html", "801-vmem-duplicated_8cc" ],
    [ "802-pte-page.cc", "802-pte-page_8cc.html", "802-pte-page_8cc" ],
    [ "803-vmem-offset.cc", "803-vmem-offset_8cc.html", "803-vmem-offset_8cc" ],
    [ "900-btb-bounds-check.cc", "900-btb-bounds-check_8cc.html", "900-btb-bounds-check_8cc" ],
    [ "instr.cc", "instr_8cc.html", null ],
    [ "instr.h", "instr_8h.html", "instr_8h" ],
    [ "mocks.hpp", "mocks_8hpp.html", [
      [ "do_nothing_MRC", "classdo__nothing__MRC.html", "classdo__nothing__MRC" ],
      [ "packet", "structdo__nothing__MRC_1_1packet.html", "structdo__nothing__MRC_1_1packet" ],
      [ "filter_MRC", "classfilter__MRC.html", "classfilter__MRC" ],
      [ "packet", "structfilter__MRC_1_1packet.html", "structfilter__MRC_1_1packet" ],
      [ "release_MRC", "classrelease__MRC.html", "classrelease__MRC" ],
      [ "counting_MRP", "structcounting__MRP.html", "structcounting__MRP" ],
      [ "queue_issue_MRP", "structqueue__issue__MRP.html", "structqueue__issue__MRP" ],
      [ "result_data", "structqueue__issue__MRP_1_1result__data.html", "structqueue__issue__MRP_1_1result__data" ],
      [ "to_wq_MRP", "structto__wq__MRP.html", "structto__wq__MRP" ],
      [ "to_rq_MRP", "structto__rq__MRP.html", "structto__rq__MRP" ],
      [ "to_pq_MRP", "structto__pq__MRP.html", "structto__pq__MRP" ]
    ] ],
    [ "pref_interface.h", "pref__interface_8h.html", [
      [ "pref_cache_operate_interface", "structtest_1_1pref__cache__operate__interface.html", "structtest_1_1pref__cache__operate__interface" ]
    ] ],
    [ "repl_interface.h", "repl__interface_8h.html", [
      [ "repl_update_interface", "structtest_1_1repl__update__interface.html", "structtest_1_1repl__update__interface" ]
    ] ]
];