var hierarchy =
[
    [ "DRAM_CHANNEL::BANK_REQUEST", "structDRAM__CHANNEL_1_1BANK__REQUEST.html", null ],
    [ "champsim::msl::base_fwcounter< val_type, MAXVAL, MINVAL >", "classchampsim_1_1msl_1_1base__fwcounter.html", null ],
    [ "std::basic_streambuf", null, [
      [ "champsim::inf_istream< Tag, StreamType >::inf_streambuf< IStrm >", "classchampsim_1_1inf__istream_1_1inf__streambuf.html", null ]
    ] ],
    [ "BasicBTB< SETS, WAYS >", "classBasicBTB.html", null ],
    [ "bentry", "classbentry.html", null ],
    [ "CACHE::BLOCK", "structCACHE_1_1BLOCK.html", null ],
    [ "champsim::msl::lru_table< T, SetProj, TagProj >::block_t", "structchampsim_1_1msl_1_1lru__table_1_1block__t.html", null ],
    [ "std::bool_constant", null, [
      [ "champsim::is_specialization< T, Primary >", "structchampsim_1_1is__specialization.html", null ]
    ] ],
    [ "CACHE::Builder< P_FLAG, R_FLAG >", "classCACHE_1_1Builder.html", null ],
    [ "O3_CPU::Builder< B_FLAG, T_FLAG >", "classO3__CPU_1_1Builder.html", null ],
    [ "PageTableWalker::Builder", "classPageTableWalker_1_1Builder.html", null ],
    [ "CACHE::builder_conversion_tag", "classCACHE_1_1builder__conversion__tag.html", null ],
    [ "O3_CPU::builder_conversion_tag", "classO3__CPU_1_1builder__conversion__tag.html", null ],
    [ "champsim::bulk_tracereader< T, F >", "classchampsim_1_1bulk__tracereader.html", null ],
    [ "champsim::decomp_tags::bzip2_tag_t", "structchampsim_1_1decomp__tags_1_1bzip2__tag__t.html", null ],
    [ "champsim::cache_queue_stats", "structchampsim_1_1cache__queue__stats.html", null ],
    [ "cache_stats", "structcache__stats.html", null ],
    [ "CacheBus", "classCacheBus.html", null ],
    [ "champsim::channel", "classchampsim_1_1channel.html", null ],
    [ "cloudsuite_instr", "structcloudsuite__instr.html", null ],
    [ "counting_MRP", "structcounting__MRP.html", null ],
    [ "cpu_stats", "structcpu__stats.html", null ],
    [ "champsim::detail::detector< Default, AlwaysVoid, Op, Args >", "structchampsim_1_1detail_1_1detector.html", null ],
    [ "champsim::detail::detector< Default, std::void_t< Op< Args... > >, Op, Args... >", "structchampsim_1_1detail_1_1detector_3_01Default_00_01std_1_1void__t_3_01Op_3_01Args_8_8_8_01_4_b2a4762ed19d4b9fdf374716eceaa0f9.html", null ],
    [ "O3_CPU::dib_shift", "structO3__CPU_1_1dib__shift.html", null ],
    [ "DRAM_CHANNEL", "structDRAM__CHANNEL.html", null ],
    [ "dram_stats", "structdram__stats.html", null ],
    [ "champsim::decomp_tags::detail::end_deleter< State, R, Del >", "structchampsim_1_1decomp__tags_1_1detail_1_1end__deleter.html", null ],
    [ "BasicBTB< SETS, WAYS >::ENTRY", "structBasicBTB_1_1ENTRY.html", null ],
    [ "champsim::environment", "structchampsim_1_1environment.html", null ],
    [ "std::exception", null, [
      [ "champsim::deadlock", "structchampsim_1_1deadlock.html", null ]
    ] ],
    [ "config.filewrite.FileWriter", "classconfig_1_1filewrite_1_1FileWriter.html", null ],
    [ "champsim::detail::fmtstr_type_finder< typename >", "structchampsim_1_1detail_1_1fmtstr__type__finder.html", null ],
    [ "champsim::detail::fmtstr_type_finder< std::tuple< Args... > >", "structchampsim_1_1detail_1_1fmtstr__type__finder_3_01std_1_1tuple_3_01Args_8_8_8_01_4_01_4.html", null ],
    [ "folded_history", "classfolded__history.html", null ],
    [ "my_predictor::folded_history", "classmy__predictor_1_1folded__history.html", null ],
    [ "python.test_parse.FoundMoreContext", "classpython_1_1test__parse_1_1FoundMoreContext.html", null ],
    [ "gentry", "classgentry.html", null ],
    [ "my_predictor::gentry", "classmy__predictor_1_1gentry.html", null ],
    [ "spp::GLOBAL_REGISTER", "classspp_1_1GLOBAL__REGISTER.html", null ],
    [ "champsim::decomp_tags::gzip_tag_t< window, compression >", "structchampsim_1_1decomp__tags_1_1gzip__tag__t.html", null ],
    [ "champsim::inf_istream< Tag, StreamType >", "structchampsim_1_1inf__istream.html", null ],
    [ "input_instr", "structinput__instr.html", null ],
    [ "champsim::json_printer", "classchampsim_1_1json__printer.html", null ],
    [ "lentry", "classlentry.html", null ],
    [ "champsim::msl::lru_table< T, SetProj, TagProj >", "classchampsim_1_1msl_1_1lru__table.html", null ],
    [ "champsim::msl::lru_table< uint64_t, dib_shift, dib_shift >", "classchampsim_1_1msl_1_1lru__table.html", null ],
    [ "LSQ_ENTRY", "structLSQ__ENTRY.html", null ],
    [ "champsim::decomp_tags::lzma_tag_t< flags >", "structchampsim_1_1decomp__tags_1_1lzma__tag__t.html", null ],
    [ "Catch::Matchers::MatcherGenericBase", null, [
      [ "AdjDiffMatcher", "structAdjDiffMatcher.html", null ],
      [ "MonotonicallyIncreasingMatcher", "structMonotonicallyIncreasingMatcher.html", null ],
      [ "StrideMatcher", "structStrideMatcher.html", null ],
      [ "StrideMatcher", "structStrideMatcher.html", null ]
    ] ],
    [ "merge_testbed", "structmerge__testbed.html", null ],
    [ "CACHE::module_concept", "structCACHE_1_1module__concept.html", [
      [ "CACHE::module_model< P_FLAG, R_FLAG >", "structCACHE_1_1module__model.html", null ]
    ] ],
    [ "O3_CPU::module_concept", "structO3__CPU_1_1module__concept.html", [
      [ "O3_CPU::module_model< B_FLAG, T_FLAG >", "structO3__CPU_1_1module__model.html", null ]
    ] ],
    [ "config.modules.ModuleSearchContext", "classconfig_1_1modules_1_1ModuleSearchContext.html", null ],
    [ "CACHE::mshr_type", "structCACHE_1_1mshr__type.html", null ],
    [ "PageTableWalker::mshr_type", "structPageTableWalker_1_1mshr__type.html", null ],
    [ "my_predictor", "classmy__predictor.html", null ],
    [ "champsim::nonesuch", "structchampsim_1_1nonesuch.html", null ],
    [ "ooo_model_instr", "structooo__model__instr.html", null ],
    [ "champsim::operable", "classchampsim_1_1operable.html", [
      [ "CACHE", "classCACHE.html", null ],
      [ "MEMORY_CONTROLLER", "classMEMORY__CONTROLLER.html", null ],
      [ "O3_CPU", "classO3__CPU.html", null ],
      [ "PageTableWalker", "classPageTableWalker.html", null ],
      [ "do_nothing_MRC", "classdo__nothing__MRC.html", null ],
      [ "filter_MRC", "classfilter__MRC.html", null ],
      [ "queue_issue_MRP", "structqueue__issue__MRP.html", [
        [ "to_pq_MRP", "structto__pq__MRP.html", null ],
        [ "to_rq_MRP", "structto__rq__MRP.html", null ],
        [ "to_wq_MRP", "structto__wq__MRP.html", null ]
      ] ],
      [ "release_MRC", "classrelease__MRC.html", null ]
    ] ],
    [ "python.test_parse.PassthroughContext", "classpython_1_1test__parse_1_1PassthroughContext.html", null ],
    [ "spp::PATTERN_TABLE", "classspp_1_1PATTERN__TABLE.html", null ],
    [ "champsim::phase_info", "structchampsim_1_1phase__info.html", null ],
    [ "champsim::phase_stats", "structchampsim_1_1phase__stats.html", null ],
    [ "champsim::plain_printer", "classchampsim_1_1plain__printer.html", null ],
    [ "PREDICTOR", "classPREDICTOR.html", null ],
    [ "test::pref_cache_operate_interface", "structtest_1_1pref__cache__operate__interface.html", null ],
    [ "spp::PREFETCH_FILTER", "classspp_1_1PREFETCH__FILTER.html", null ],
    [ "PageTableWalker::pscl_entry", "structPageTableWalker_1_1pscl__entry.html", null ],
    [ "PageTableWalker::pscl_indexer", "structPageTableWalker_1_1pscl__indexer.html", null ],
    [ "RAS< RAS_SIZE, CALL_INSTR_SIZE_TRACKERS >", "classRAS.html", null ],
    [ "champsim::tracereader::reader_concept", "structchampsim_1_1tracereader_1_1reader__concept.html", [
      [ "champsim::tracereader::reader_model< T >", "structchampsim_1_1tracereader_1_1reader__model.html", null ]
    ] ],
    [ "my_predictor::regionentry", "classmy__predictor_1_1regionentry.html", null ],
    [ "champsim::repeatable< T, Args >", "structchampsim_1_1repeatable.html", null ],
    [ "test::repl_update_interface", "structtest_1_1repl__update__interface.html", null ],
    [ "champsim::channel::request", "structchampsim_1_1channel_1_1request.html", [
      [ "do_nothing_MRC::packet", "structdo__nothing__MRC_1_1packet.html", null ],
      [ "filter_MRC::packet", "structfilter__MRC_1_1packet.html", null ]
    ] ],
    [ "DRAM_CHANNEL::request_type", "structDRAM__CHANNEL_1_1request__type.html", null ],
    [ "champsim::channel::response", "structchampsim_1_1channel_1_1response.html", null ],
    [ "queue_issue_MRP::result_data", "structqueue__issue__MRP_1_1result__data.html", null ],
    [ "spp::SIGNATURE_TABLE", "classspp_1_1SIGNATURE__TABLE.html", null ],
    [ "my_predictor::specentry", "classmy__predictor_1_1specentry.html", null ],
    [ "champsim::msl::detail::table_indexer< T >", "structchampsim_1_1msl_1_1detail_1_1table__indexer.html", null ],
    [ "champsim::msl::detail::table_tagger< T >", "structchampsim_1_1msl_1_1detail_1_1table__tagger.html", null ],
    [ "CACHE::tag_lookup_type", "structCACHE_1_1tag__lookup__type.html", null ],
    [ "champsim::detail::take_last< T >", "structchampsim_1_1detail_1_1take__last.html", null ],
    [ "unittest.TestCase", null, [
      [ "python.test_defaults.DTLBPathTests", "classpython_1_1test__defaults_1_1DTLBPathTests.html", null ],
      [ "python.test_defaults.ITLBPathTests", "classpython_1_1test__defaults_1_1ITLBPathTests.html", null ],
      [ "python.test_defaults.L1DPathTests", "classpython_1_1test__defaults_1_1L1DPathTests.html", null ],
      [ "python.test_defaults.L1IPathTests", "classpython_1_1test__defaults_1_1L1IPathTests.html", null ],
      [ "python.test_filewrite.FilesAreDifferentTests", "classpython_1_1test__filewrite_1_1FilesAreDifferentTests.html", null ],
      [ "python.test_instantiation_file.VectorStringgTest", "classpython_1_1test__instantiation__file_1_1VectorStringgTest.html", null ],
      [ "python.test_makefile.EachInDictListTests", "classpython_1_1test__makefile_1_1EachInDictListTests.html", null ],
      [ "python.test_parse.CompileAllModulesTests", "classpython_1_1test__parse_1_1CompileAllModulesTests.html", null ],
      [ "python.test_parse.ConfigRootPassthroughParseTests", "classpython_1_1test__parse_1_1ConfigRootPassthroughParseTests.html", null ],
      [ "python.test_parse.DuplicateToLengthTests", "classpython_1_1test__parse_1_1DuplicateToLengthTests.html", null ],
      [ "python.test_parse.EnvironmentParseTests", "classpython_1_1test__parse_1_1EnvironmentParseTests.html", null ],
      [ "python.test_parse.ExecutableNameTests", "classpython_1_1test__parse_1_1ExecutableNameTests.html", null ],
      [ "python.test_parse.FilterInaccessibleTests", "classpython_1_1test__parse_1_1FilterInaccessibleTests.html", null ],
      [ "python.test_parse.NormalizeConfigTest", "classpython_1_1test__parse_1_1NormalizeConfigTest.html", null ],
      [ "python.test_parse.ParseNormalizedTests", "classpython_1_1test__parse_1_1ParseNormalizedTests.html", null ],
      [ "python.test_parse.SplitStringOrListTests", "classpython_1_1test__parse_1_1SplitStringOrListTests.html", null ],
      [ "python.test_util.ChainTests", "classpython_1_1test__util_1_1ChainTests.html", null ],
      [ "python.test_util.CombineNamedTests", "classpython_1_1test__util_1_1CombineNamedTests.html", null ],
      [ "python.test_util.ExtendEachTests", "classpython_1_1test__util_1_1ExtendEachTests.html", null ],
      [ "python.test_util.IterSystemTests", "classpython_1_1test__util_1_1IterSystemTests.html", null ],
      [ "python.test_util.SubdictTests", "classpython_1_1test__util_1_1SubdictTests.html", null ],
      [ "python.test_util.UpperLevelsForTests", "classpython_1_1test__util_1_1UpperLevelsForTests.html", null ],
      [ "python.test_util.WrapListTests", "classpython_1_1test__util_1_1WrapListTests.html", null ]
    ] ],
    [ "champsim::tracereader", "classchampsim_1_1tracereader.html", null ],
    [ "VirtualMemory", "classVirtualMemory.html", null ]
];